[package]
name = "amphipod"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
# regex = "1"
clap = "2.33.0"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
